{% set name = "sagemaker-studio-analytics-extension" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5b73c035a19cc1120a11cd72e138fe22efd47c20ad1b558b6b7009ba17154358

build:
  entry_points:
    - sm_analytics_runtime_check=sagemaker_studio_analytics_extension.utils.runtime_check:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=40.8.0
  run:
    - python >=3.6
    - boto3 >=1.26.49,<2.0
    - sparkmagic ==0.21.0
    - sagemaker-studio-sparkmagic-lib >=0.1.1
    - filelock >=3.0.12

test:
  imports:
    - sagemaker_studio_analytics_extension
  commands:
    # including `pip check` here is recommended, but excluded for now until downstream dependency is fixed: https://github.com/conda-forge/sparkmagic-feedstock/issues/36
    - sm_analytics_runtime_check --help
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker
  summary: SageMaker Studio Analytics Extension
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pilgd-aws
    - joshuatowner
    - nileshvd
    - HariniNarayanan
    - just4brown
    - nargokul
    - pintaoz-aws
    - benieric
    - mufaddal-rohawala
    - C24IO
    - Aditi2424
    - akrishna1995
    - bhadrip
    - aws-jasakshi
    - aws-prayags
    - sgganjo
    - aws-jeffrey-yang
    - henrywa2
    - aws-pavankks
    - aakashmandavilli96
