{% set name = "sagemaker-studio-analytics-extension" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 56a073cbfcf6dc596c05ddaf25baa2cc6db6eae80528e46a30a113d209755d67

build:
  entry_points:
    - sm_analytics_runtime_check=sagemaker_studio_analytics_extension.utils.runtime_check:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=40.8.0
  run:
    - python >={{ python_min }}
    - boto3 >=1.26.49,<2.0
    - sparkmagic ==0.21.0
    - sagemaker-studio-sparkmagic-lib >=0.1.1
    - filelock >=3.0.12

test:
  imports:
    - sagemaker_studio_analytics_extension
  commands:
    # including `pip check` here is recommended, but excluded for now until downstream dependency is fixed: https://github.com/conda-forge/sparkmagic-feedstock/issues/36
    - sm_analytics_runtime_check --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://aws.amazon.com/sagemaker
  summary: SageMaker Studio Analytics Extension
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nileshvd
    - HariniNarayanan
    - just4brown
    - nargokul
    - pintaoz-aws
    - benieric
    - mufaddal-rohawala
    - C24IO
    - Aditi2424
    - akrishna1995
    - bhadrip
