{% set name = "sagemaker-studio-analytics-extension" %}
{% set version = "0.0.22" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sagemaker-studio-analytics-extension-{{ version }}.tar.gz
  sha256: 64cc55474b097f07963186a0405767afa16e8b1fa6401b031915769929e418fd

build:
  entry_points:
    - sm_analytics_runtime_check=sagemaker_studio_analytics_extension.utils.runtime_check:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - boto3 >=1.26.49,<2.0
    - sparkmagic ==0.21.0
    - sagemaker-studio-sparkmagic-lib >=0.1.1
    - filelock >=3.0.12

test:
  imports:
    - sagemaker_studio_analytics_extension
  commands:
    # including `pip check` here is recommended, but excluded for now until downstream dependency is fixed: https://github.com/conda-forge/sparkmagic-feedstock/issues/36
    - sm_analytics_runtime_check --help
  requires:
    - pip

about:
  home: https://aws.amazon.com/sagemaker
  summary: SageMaker Studio Analytics Extension
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - HariniNarayanan
    - just4brown
    - nargokul
    - pintaoz-aws
    - benieric
    - mufaddal-rohawala
    - C24IO
    - Aditi2424
    - akrishna1995
